AWSTemplateFormatVersion: '2010-09-09'
Description: SMR reduce layer
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: python3.8
    MemorySize: 128
    Timeout: 60
    Tracing: Active
    Layers:
      - !Sub 'arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14'
      # NOTE: this is causing SAM local issues, need to hard code the account id
      - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:xray-python38:2'
Parameters:
  pCountersArn:
    Type: String
  pShuffleArn:
    Type: String
  pAslBucket:
    Type: String
  pAslKey:
    Type: String
  pPackage:
    Type: String
  pShuffleBucket:
    Type: String
Resources:
  # Lambda
  FnRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/service-role/'
      Policies:
        - PolicyName: cloudwatch-insights
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                Resource: '*'
        - PolicyName: cloudwatch-logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: 'arn:aws:logs:*:*:log-group:*:*'
        - PolicyName: xray
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                  - xray:GetSamplingRules
                  - xray:GetSamplingTargets
                  - xray:GetSamplingStatisticSummaries
                Resource: '*'
        - PolicyName: codeguru
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - codeguru-profiler:ConfigureAgent
                  - codeguru-profiler:CreateProfilingGroup
                  - codeguru-profiler:PostAgentProfile
                Resource: 'arn:aws:codeguru-profiler:*:*:profilingGroup/*'
        - PolicyName: dynamodb
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:DeleteItem
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                Resource:
                  - !Ref pCountersArn
                  - !Ref pShuffleArn
        - PolicyName: s3-bucket
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:List*
                Resource:
                  - !Sub 'arn:aws:s3:::${pShuffleBucket}'
        - PolicyName: s3-object
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:Put*
                Resource:
                  - !Sub 'arn:aws:s3:::${pShuffleBucket}/*'
  FnGate:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: fn_gate.handler
      Role: !GetAtt FnRole.Arn
      Environment:
        Variables:
          TABLE_COUNTERS: !Select [1, !Split ["/", !Ref pCountersArn]]
          TABLE_SHUFFLE: !Select [1, !Split ["/", !Ref pShuffleArn]]
          BUCKET_SHUFFLE: !Ref pShuffleBucket
      Layers:
        - !Ref pPackage
  FnGateLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${FnGate}'
  FnReduce1:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: fn_reduce1.handler
      Role: !GetAtt FnRole.Arn
      Environment:
        Variables:
          TABLE_SHUFFLE: !Select [1, !Split ["/", !Ref pShuffleArn]]
          BUCKET_SHUFFLE: !Ref pShuffleBucket
      MemorySize: 10240
      Timeout: 900
  FnReduce1LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${FnReduce1}'
      RetentionInDays: 7
  FnReduce2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: fn_reduce2.handler
      Role: !GetAtt FnRole.Arn
      Environment:
        Variables:
          TABLE_SHUFFLE: !Select [1, !Split ["/", !Ref pShuffleArn]]
          BUCKET_SHUFFLE: !Ref pShuffleBucket
  FnReduce2LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${FnReduce2}'
      RetentionInDays: 7
  # Step Function
  SFnRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/service-role/'
      Policies:
        - PolicyName: cloudwatch-logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogDelivery
                  - logs:GetLogDelivery
                  - logs:UpdateLogDelivery
                  - logs:DeleteLogDelivery
                  - logs:ListLogDeliveries
                  - logs:PutResourcePolicy
                  - logs:DescribeResourcePolicies
                  - logs:DescribeLogGroups
                Resource: "*"
        - PolicyName: lambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !GetAtt FnGate.Arn
                  - !GetAtt FnReduce1.Arn
                  - !GetAtt FnReduce2.Arn
  SFn:
    Type: AWS::StepFunctions::StateMachine
    Properties:
        DefinitionS3Location:
          Bucket: !Ref pAslBucket
          Key: !Ref pAslKey
        DefinitionSubstitutions:
          FnGate: !GetAtt FnGate.Arn
          FnReduce1: !GetAtt FnReduce1.Arn
          FnReduce2: !GetAtt FnReduce2.Arn
        LoggingConfiguration:
          Destinations:
            - CloudWatchLogsLogGroup:
                LogGroupArn: !GetAtt SFnLogGroup.Arn
          IncludeExecutionData: true
          Level: ALL
        RoleArn: !GetAtt SFnRole.Arn
        StateMachineType: STANDARD
        TracingConfiguration:
          Enabled: false
  SFnLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/sf/smr-reduce"
      RetentionInDays: 7
Outputs:
  outFnGate:
    Value: !Ref FnGate
  outFnReduce1:
    Value: !Ref FnReduce1
  outSFn:
    Value: !GetAtt SFn.Arn