AWSTemplateFormatVersion: '2010-09-09'
Description: SMR map layer
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: python3.8
    MemorySize: 128
    Timeout: 60
    Tracing: Active
    Layers:
      - !Sub 'arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14'
Parameters:
  pQueueArn:
    Type: String
  pCountersArn:
    Type: String
  pPackage:
    Type: String
Resources:
  # S3
  ShuffleBucket:
    Type: AWS::S3::Bucket
  # DynamoDB
  ShuffleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: eid
          AttributeType: S
        - AttributeName: iid
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: eid
          KeyType: HASH
        - AttributeName: iid
          KeyType: RANGE
  # Lambda
  FnRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/service-role/'
      Policies:
        - PolicyName: cloudwatch-logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: 'arn:aws:logs:*:*:log-group:*:*'
        - PolicyName: sqs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:ChangeMessageVisibility
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ReceiveMessage
                Resource: !Ref pQueueArn
        - PolicyName: dynamodb
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:BatchGetItem
                  - dynamodb:BatchWriteItem
                  - dynamodb:DeleteItem
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                Resource:
                  - !Ref pCountersArn
                  - !GetAtt ShuffleTable.Arn
        - PolicyName: s3
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:Get*
                  - s3:Put*
                Resource:
                  - !Sub '${ShuffleBucket.Arn}/*'
  Fn:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: fn.handler
      Role: !GetAtt FnRole.Arn
      Environment:
        Variables:
          TABLE_COUNTERS: !Select [1, !Split ["/", !Ref pCountersArn]]
          TABLE_SHUFFLE: !Ref ShuffleTable
          BUCKET_SHUFFLE: !Ref ShuffleBucket
      Layers:
        - !Ref pPackage
  FnLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${Fn}'
      RetentionInDays: 7
  FnMapping:
    Type: AWS::Lambda::EventSourceMapping
    Properties:
      BatchSize: 10
      Enabled: true
      EventSourceArn: !Ref pQueueArn
      FunctionName: !GetAtt Fn.Arn
Outputs:
  outFn:
    Value: !Ref Fn
  outShuffleBucket:
    Value: !Ref ShuffleBucket
  outShuffleTable:
    Value: !Ref ShuffleTable
