AWSTemplateFormatVersion: '2010-09-09'
Description: SMR ingestion layer
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: python3.8
    MemorySize: 128
    Timeout: 900
    Tracing: Active
    Layers:
      - !Sub 'arn:aws:lambda:${AWS::Region}:580247275435:layer:LambdaInsightsExtension:14'
      # - !Sub 'arn:aws:lambda:${AWS::Region}:157417159150:layer:AWSCodeGuruProfilerPythonAgentLambdaLayer:10'
      # NOTE: referencing ${AWS::AccountId} is causing SAM local issues, need to hard code the account id
      # https://github.com/aws/aws-sam-cli/issues/1736
      # https://github.com/aws/aws-sam-cli/issues/2325
      # - !Sub 'arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:layer:xray-python38:2'
      - !Sub 'arn:aws:lambda:${AWS::Region}:546275881527:layer:xray-python38:2'
Parameters:
  pBucket:
    Type: String
  pNumTasks:
    Type: String
  pBatchSize:
    Type: String
  pBatchLimit:
    Type: String
  pPackage:
    Type: String
  pProfilingGroup:
    Type: String
    Default: smr-ingest
Resources:
  # DynamoDB
  Counters:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: id
          KeyType: HASH
  # SQS
  IngestQ:
    Type: AWS::SQS::Queue
    Properties:
      # ContentBasedDeduplication: true
      # DeduplicationScope: queue
      DelaySeconds: 0
      # FifoQueue: true
      # FifoThroughputLimit: perQueue
      MessageRetentionPeriod: 600
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DLQ.Arn
        maxReceiveCount: 2
      VisibilityTimeout: 60
  DLQ:
    Type: AWS::SQS::Queue
    Properties:
      # ContentBasedDeduplication: true
      # DeduplicationScope: queue
      DelaySeconds: 0
      # FifoQueue: true
      # FifoThroughputLimit: perQueue
      MessageRetentionPeriod: 300
      VisibilityTimeout: 60
  # CodeGuru
  CodeProfile:
    Type: AWS::CodeGuruProfiler::ProfilingGroup
    Properties:
      ComputePlatform: AWSLambda
      ProfilingGroupName: !Ref pProfilingGroup
      AgentPermissions:
        Principals:
          - !GetAtt FnRole.Arn
  # Lambda
  FnRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/service-role/'
      Policies:
        - PolicyName: cloudwatch-insights
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                Resource: '*'
        - PolicyName: cloudwatch-logs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource: 'arn:aws:logs:*:*:log-group:*:*'
        - PolicyName: xray
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - xray:PutTraceSegments
                  - xray:PutTelemetryRecords
                  - xray:GetSamplingRules
                  - xray:GetSamplingTargets
                  - xray:GetSamplingStatisticSummaries
                Resource: '*'
        - PolicyName: codeguru
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - codeguru-profiler:ConfigureAgent
                  - codeguru-profiler:CreateProfilingGroup
                  - codeguru-profiler:PostAgentProfile
                Resource: '*'
        - PolicyName: s3
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: !Sub 'arn:aws:s3:::${pBucket}/*'
        - PolicyName: dynamodb
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:DeleteItem
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:Query
                  - dynamodb:Scan
                  - dynamodb:UpdateItem
                Resource: !GetAtt Counters.Arn
        - PolicyName: sqs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - sqs:DeleteMessage
                  - sqs:ReceiveMessage
                  - sqs:SendMessage
                Resource: !GetAtt IngestQ.Arn
  FnIngest:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: fn_ingest.handler
      Role: !GetAtt FnRole.Arn
      Environment:
        Variables:
          BUCKET: !Ref pBucket
          COUNTERS_TABLE: !Ref Counters
          SQS_QUEUE: !Ref IngestQ
          SQS_BATCH_SIZE: !Ref pBatchSize
          SQS_BATCH_LIMIT: !Ref pBatchLimit
          NUM_TASKS: !Ref pNumTasks
          # AWS_LAMBDA_EXEC_WRAPPER: /opt/codeguru_profiler_lambda_exec
          AWS_CODEGURU_PROFILER_GROUP_NAME: !Ref pProfilingGroup
          AWS_CODEGURU_PROFILER_GROUP_ARN: !GetAtt CodeProfile.Arn
          AWS_CODEGURU_PROFILER_TARGET_REGION: !Ref AWS::Region
      Layers:
        - !Ref pPackage
      MemorySize: 3072
  FnIngestLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${FnIngest}'
      RetentionInDays: 7
  FnPrep:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src
      Handler: fn_prep.handler
      Role: !GetAtt FnRole.Arn
  FnPrepLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${FnPrep}'
      RetentionInDays: 7
Outputs:
  outCounters:
    Value: !Ref Counters
  outCountersArn:
    Value: !GetAtt Counters.Arn
  outIngestQ:
    Value: !Ref IngestQ
  outIngestQArn:
    Value: !GetAtt IngestQ.Arn
  outDLQ:
    Value: !Ref DLQ
  outFnIngest:
    Value: !Ref FnIngest
  outFnPrep:
    Value: !Ref FnPrep